<?php
declare(strict_types=1);
require_once __DIR__ . '/config.php';

function start_app_session(): void { if (session_status() !== PHP_SESSION_ACTIVE) session_start(); }
function db(bool $withDatabase = true): mysqli { mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT); $c = new mysqli(DB_HOST, DB_USER, DB_PASS, $withDatabase ? DB_NAME : ''); $c->set_charset('utf8mb4'); if ($withDatabase) ensure_schema($c); return $c; }
function ensure_column(mysqli $c, string $table, string $column, string $definition): void { $s=$c->prepare('SELECT COUNT(*) total FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?'); $s->bind_param('ss',$table,$column); $s->execute(); if ((int)$s->get_result()->fetch_assoc()['total']===0) $c->query('ALTER TABLE `'.$table.'` ADD COLUMN `'.$column.'` '.$definition); }
function ensure_schema(mysqli $c): void { static $done=false; if($done)return; $done=true; $c->query('CREATE TABLE IF NOT EXISTS sellers (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,active TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci'); if($c->query("SHOW TABLES LIKE 'orders'")->num_rows>0){ ensure_column($c,'orders','priority','VARCHAR(20) NOT NULL DEFAULT "normal"'); ensure_column($c,'orders','internal_note','TEXT NULL'); $c->query('CREATE TABLE IF NOT EXISTS order_events (id INT AUTO_INCREMENT PRIMARY KEY,order_id INT NOT NULL,event_type VARCHAR(40) NOT NULL,description VARCHAR(255) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci'); } if((int)$c->query('SELECT COUNT(*) total FROM sellers')->fetch_assoc()['total']===0){ $s=$c->prepare('INSERT INTO sellers (name) VALUES (?)'); foreach(['Vendedora 1','Vendedora 2'] as $n){$s->bind_param('s',$n);$s->execute();}} }
function h(?string $v): string { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
function status_label(string $s): string { return match($s){'novo'=>'Novo','separando'=>'Separando','concluido'=>'Concluido','cancelado'=>'Cancelado',default=>ucfirst($s)}; }
function status_class(string $s): string { return match($s){'novo'=>'status-new','separando'=>'status-progress','concluido'=>'status-done','cancelado'=>'status-cancel',default=>'status-new'}; }
function priority_label(string $p): string { return $p==='urgente'?'Urgente':'Normal'; }
function priority_class(string $p): string { return $p==='urgente'?'priority-urgent':'priority-normal'; }
function redirect(string $p): never { header('Location: '.$p); exit; }
function current_role(): string { start_app_session(); return $_SESSION['role'] ?? ''; }
function current_seller_name(): string { start_app_session(); return $_SESSION['seller_name'] ?? ''; }
function require_role(array $roles): void { if(!in_array(current_role(),$roles,true)){ $script=$_SERVER['SCRIPT_NAME']??''; redirect(str_contains($script,'/api/')?'../login.php':'login.php'); } }
function role_label(string $r): string { return match($r){'admin'=>'Admin','estoque'=>'Estoque','vendedora'=>'Vendedora',default=>''}; }
function fetch_products(mysqli $c,bool $onlyActive=true): array { return $c->query('SELECT * FROM products'.($onlyActive?' WHERE active=1':'').' ORDER BY name')->fetch_all(MYSQLI_ASSOC); }
function fetch_popular_products(mysqli $c,int $limit=20): array { $limit=max(1,min(100,$limit)); return $c->query('SELECT p.id,p.sku,p.name,p.unit,p.stock_qty,p.active,p.created_at,COALESCE(SUM(oi.quantity),0) total_requested FROM products p LEFT JOIN order_items oi ON oi.product_id=p.id WHERE p.active=1 GROUP BY p.id,p.sku,p.name,p.unit,p.stock_qty,p.active,p.created_at ORDER BY total_requested DESC,p.name LIMIT '.$limit)->fetch_all(MYSQLI_ASSOC); }
function search_products(mysqli $c,string $q,int $limit=20): array { $q=trim($q); if($q==='') return fetch_popular_products($c,$limit); $limit=max(1,min(100,$limit)); $like='%'.$q.'%'; $s=$c->prepare('SELECT p.id,p.sku,p.name,p.unit,p.stock_qty,p.active,p.created_at,COALESCE(SUM(oi.quantity),0) total_requested FROM products p LEFT JOIN order_items oi ON oi.product_id=p.id WHERE p.active=1 AND (p.name LIKE ? OR p.sku LIKE ?) GROUP BY p.id,p.sku,p.name,p.unit,p.stock_qty,p.active,p.created_at ORDER BY total_requested DESC,p.name LIMIT '.$limit); $s->bind_param('ss',$like,$like); $s->execute(); return $s->get_result()->fetch_all(MYSQLI_ASSOC); }
function fetch_sellers(mysqli $c,bool $onlyActive=true): array { return $c->query('SELECT * FROM sellers'.($onlyActive?' WHERE active=1':'').' ORDER BY name')->fetch_all(MYSQLI_ASSOC); }
function fetch_order(mysqli $c,int $id): ?array { $s=$c->prepare('SELECT * FROM orders WHERE id=?'); $s->bind_param('i',$id); $s->execute(); $o=$s->get_result()->fetch_assoc(); if(!$o)return null; $s=$c->prepare('SELECT oi.*,p.name,p.sku,p.unit FROM order_items oi JOIN products p ON p.id=oi.product_id WHERE oi.order_id=? ORDER BY p.name'); $s->bind_param('i',$id); $s->execute(); $o['items']=$s->get_result()->fetch_all(MYSQLI_ASSOC); $s=$c->prepare('SELECT * FROM order_events WHERE order_id=? ORDER BY created_at ASC,id ASC'); $s->bind_param('i',$id); $s->execute(); $o['events']=$s->get_result()->fetch_all(MYSQLI_ASSOC); return $o; }
function fetch_orders_by_seller(mysqli $c,string $seller): array { $s=$c->prepare('SELECT o.*,COUNT(oi.id) item_count FROM orders o LEFT JOIN order_items oi ON oi.order_id=o.id WHERE o.seller_name=? GROUP BY o.id ORDER BY o.created_at DESC LIMIT 20'); $s->bind_param('s',$seller); $s->execute(); return attach_print_flags($c,$s->get_result()->fetch_all(MYSQLI_ASSOC)); }
function can_seller_cancel(array $o): bool { return $o['status']==='novo'; }
function attach_print_flags(mysqli $c,array $orders): array { if(!$orders)return $orders; $ids=implode(',',array_map(fn($o)=>(int)$o['id'],$orders)); $printed=[]; $r=$c->query('SELECT order_id,MAX(created_at) printed_at FROM order_events WHERE event_type="print" AND order_id IN ('.$ids.') GROUP BY order_id'); while($row=$r->fetch_assoc()) $printed[(int)$row['order_id']]=$row['printed_at']; foreach($orders as &$o)$o['printed_at']=$printed[(int)$o['id']]??null; return $orders; }
function add_order_event(mysqli $c,int $id,string $type,string $desc): void { $s=$c->prepare('INSERT INTO order_events (order_id,event_type,description) VALUES (?,?,?)'); $s->bind_param('iss',$id,$type,$desc); $s->execute(); }
function update_order_status(mysqli $c,int $id,string $status): void { $s=$c->prepare('UPDATE orders SET status=? WHERE id=?'); $s->bind_param('si',$status,$id); $s->execute(); add_order_event($c,$id,'status','Status alterado para '.status_label($status)); }
function update_internal_note(mysqli $c,int $id,string $note): void { $s=$c->prepare('UPDATE orders SET internal_note=? WHERE id=?'); $s->bind_param('si',$note,$id); $s->execute(); add_order_event($c,$id,'note','Observacao interna atualizada'); }
function printer_text(string $t): string { $t=strtr($t,['á'=>'a','à'=>'a','ã'=>'a','â'=>'a','é'=>'e','ê'=>'e','í'=>'i','ó'=>'o','ô'=>'o','õ'=>'o','ú'=>'u','ç'=>'c','Á'=>'A','É'=>'E','Í'=>'I','Ó'=>'O','Ú'=>'U','Ç'=>'C']); return preg_replace('/[^\x09\x0A\x0D\x20-\x7E]/','',$t)??$t; }
function receipt_center(string $t,int $w=42): string { $t=printer_text($t); return strlen($t)>=$w?substr($t,0,$w):str_repeat(' ',intdiv($w-strlen($t),2)).$t; }
function receipt_columns(string $l,string $r,int $w=42): string { $rw=12; $lw=$w-$rw; return str_pad(substr(printer_text($l),0,$lw),$lw).str_pad(substr(printer_text($r),0,$rw),$rw,' ',STR_PAD_LEFT); }
function receipt_wrap(string $t,int $w=42): array { return explode("\n",wordwrap(printer_text($t),$w,"\n",true)); }
function receipt_payload(array $o): string { $line=str_repeat('-',42)."\r\n"; $p="\x1B@\x07".receipt_center(STORE_NAME)."\r\n".receipt_center('Pedido #'.(int)$o['id'])."\r\n".receipt_center(date('d/m/Y H:i',strtotime($o['created_at'])))."\r\n".$line; $p.='Vendedora: '.printer_text($o['seller_name'])."\r\n".'Prioridade: '.printer_text(priority_label($o['priority']??'normal'))."\r\n".'Status: '.printer_text(status_label($o['status']))."\r\n"; if(!empty($o['notes']))$p.='Obs: '.printer_text($o['notes'])."\r\n"; $p.=$line.receipt_columns('Produto','Qtd')."\r\n".$line; foreach($o['items'] as $it){ $lines=receipt_wrap($it['name'],30); $qty=rtrim(rtrim((string)$it['quantity'],'0'),'.').' '.printer_text($it['unit']); $p.=receipt_columns($lines[0]??'',$qty)."\r\n"; foreach(array_slice($lines,1) as $lt)$p.=printer_text($lt)."\r\n"; if(!empty($it['sku']))$p.=printer_text($it['sku'])."\r\n"; $p.=$line; } return $p."\r\n".receipt_center('Conferido por: __________________')."\r\n\x1B\x64\x06\x1B\x69"; }
function printer_config_path(): string { return __DIR__.'/data/printer.json'; }
function default_printer_config(): array { return ['name'=>PRINTER_PORT,'port'=>PRINTER_PORT,'is_default'=>false]; }
function available_windows_printers(): array { if(!function_exists('exec'))return []; $cmd='powershell -NoProfile -ExecutionPolicy Bypass -Command '.escapeshellarg('$p=New-Object -ComObject WScript.Network; $items=$p.EnumPrinterConnections(); $rows=@(); for ($i=0; $i -lt $items.Count(); $i+=2) { $rows += [PSCustomObject]@{PortName=$items.Item($i); Name=$items.Item($i+1); Default=$false} }; $rows | ConvertTo-Json -Compress'); @exec($cmd,$out,$code); $d=$out?json_decode(implode("\n",$out),true):null; if(!$d)return []; $rows=isset($d['Name'])?[$d]:$d; $p=[]; foreach($rows as $r){ if(!empty($r['Name']))$p[]=['name'=>(string)$r['Name'],'port'=>(string)($r['PortName']??''),'is_default'=>(bool)($r['Default']??false)]; } usort($p,fn($a,$b)=>strcasecmp($a['name'],$b['name'])); return $p; }
function active_printer_config(): array { $path=printer_config_path(); if(is_file($path)){ $d=json_decode((string)file_get_contents($path),true); if(is_array($d)&&!empty($d['name']))return ['name'=>(string)$d['name'],'port'=>(string)($d['port']??''),'is_default'=>(bool)($d['is_default']??false)]; } return default_printer_config(); }
function active_printer_label(): string { $p=active_printer_config(); return empty($p['port'])||$p['port']===$p['name']?$p['name']:$p['name'].' ('.$p['port'].')'; }
function save_active_printer(string $name): bool { $name=trim($name); $printer=$name===PRINTER_PORT?default_printer_config():null; if(!$printer){ foreach(available_windows_printers() as $x){ if(hash_equals($x['name'],$name)){ $printer=$x; break; } } } if(!$printer)return false; if(!is_dir(__DIR__.'/data'))mkdir(__DIR__.'/data',0775,true); return file_put_contents(printer_config_path(),json_encode($printer,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE))!==false; }
function send_to_printer_port(string $payload,string $portName): array { if(!DIRECT_PRINT_ENABLED)return ['ok'=>false,'message'=>'Impressao direta desativada.']; $port=rtrim($portName,':').':'; if(function_exists('exec'))@exec('mode '.escapeshellarg($port).' '.PRINTER_MODE); $h=@fopen($port,'wb'); if($h){fwrite($h,$payload);fclose($h);return ['ok'=>true,'message'=>'Enviado para '.rtrim($port,':').'.'];} $tmp=tempnam(sys_get_temp_dir(),'pedido_'); if($tmp!==false&&function_exists('exec')){file_put_contents($tmp,$payload);@exec('cmd /C copy /B '.escapeshellarg($tmp).' '.escapeshellarg($port).' >NUL',$o,$code);@unlink($tmp); if($code===0)return ['ok'=>true,'message'=>'Enviado para '.rtrim($port,':').'.'];} return ['ok'=>false,'message'=>'Nao foi possivel abrir a porta '.rtrim($port,':').'.']; }
function send_to_printer(string $payload): array { $p=active_printer_config(); $port=strtoupper(rtrim((string)($p['port']??''),':')); return send_to_printer_port($payload,$port!==''&&str_starts_with($port,'COM')?$port:PRINTER_PORT); }
function direct_print_order(mysqli $c,int $id,string $confirmation='Impressao automatica confirmada'): array { $o=fetch_order($c,$id); if(!$o)return ['ok'=>false,'message'=>'Pedido nao encontrado.']; $r=send_to_printer(receipt_payload($o)); if($r['ok'])add_order_event($c,$id,'print',$confirmation); return $r; }
function app_header(string $title): void { $role=current_role(); ?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#0f766e"><title><?= h($title) ?> - <?= h(APP_NAME) ?></title><link rel="manifest" href="manifest.json"><link rel="icon" href="assets/icon.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/style.css?v=20260626-1"></head><body><header class="topbar"><a class="brand" href="dashboard.php"><?= h(APP_NAME) ?></a><nav class="nav"><a href="index.php">Novo pedido</a><a href="dashboard.php">Dashboard</a><a href="selecionar_impressora.php">Impressora</a><a href="relatorios.php">Relatorios</a><?php if($role==='admin'): ?><a href="produtos.php">Produtos</a><a href="vendedoras.php">Vendedoras</a><?php endif; ?><?php if($role): ?><a href="logout.php">Sair <?= h(role_label($role)) ?></a><?php endif; ?></nav></header><main class="page"><?php }
function seller_header(string $title): void { $role=current_role(); $seller=current_seller_name(); ?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#0f766e"><title><?= h($title) ?> - <?= h(APP_NAME) ?></title><link rel="manifest" href="manifest.json"><link rel="icon" href="assets/icon.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/style.css?v=20260626-1"></head><body><header class="topbar seller-only"><span class="brand"><?= h(APP_NAME) ?></span><?php if($role): ?><nav class="nav"><?php if($seller): ?><span class="nav-label"><?= h($seller) ?></span><?php endif; ?><a href="logout.php">Sair</a></nav><?php endif; ?></header><main class="page"><?php }
function app_footer(): void { ?></main><script src="assets/app.js?v=20260626-1"></script></body></html><?php }
